"""Stable domain contracts shared across application layers."""

from .enums import EvidenceKind, FileRole, FinalStatus, ReviewStatus, TaskState, TemplateStatus
from .models import (
    AtomicResult,
    ContentBlock,
    ConversionProvenance,
    DocumentContainer,
    EvidenceLocator,
    ManualDecision,
    ParseWarning,
    ReportDocument,
    ReviewInput,
    ReviewRevision,
    ReviewSource,
    ReviewTask,
    RuleResult,
    RuleDefinition,
    SourceFileCreate,
    StageFailure,
    StagedFile,
    TableCell,
    TemplateRule,
    TemplateValidationFinding,
    TemplateVersion,
)
from .ports import (
    Clock,
    DecisionRepository,
    DocumentParser,
    DocumentQuery,
    ResultRepository,
    RevisionRepository,
    TaskRepository,
)

__all__ = [
    "AtomicResult",
    "Clock",
    "ContentBlock",
    "ConversionProvenance",
    "DecisionRepository",
    "DocumentContainer",
    "DocumentParser",
    "DocumentQuery",
    "EvidenceKind",
    "EvidenceLocator",
    "FileRole",
    "FinalStatus",
    "ManualDecision",
    "ParseWarning",
    "ReportDocument",
    "ReviewInput",
    "ResultRepository",
    "ReviewStatus",
    "ReviewRevision",
    "ReviewSource",
    "ReviewTask",
    "RuleResult",
    "RuleDefinition",
    "RevisionRepository",
    "SourceFileCreate",
    "StageFailure",
    "StagedFile",
    "TableCell",
    "TaskRepository",
    "TaskState",
    "TemplateRule",
    "TemplateStatus",
    "TemplateValidationFinding",
    "TemplateVersion",
]
