"""Closed vocabulary domain enums."""

from enum import Enum


class ReviewStatus(str, Enum):
    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class FinalStatus(str, Enum):
    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class TaskState(str, Enum):
    CREATED = "CREATED"
    FILES_STAGED = "FILES_STAGED"
    PARSING = "PARSING"
    PARSED = "PARSED"
    EVALUATING = "EVALUATING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class FileRole(str, Enum):
    PRIMARY_REPORT = "PRIMARY_REPORT"
    SUPPORTING_EVIDENCE = "SUPPORTING_EVIDENCE"


class EvidenceKind(str, Enum):
    JIRA_RECORD = "JIRA_RECORD"
    PREVIOUS_STAGE_REPORT = "PREVIOUS_STAGE_REPORT"
    POWER_RECORD = "POWER_RECORD"
    REQUIREMENT_OR_CASE_MAPPING = "REQUIREMENT_OR_CASE_MAPPING"
    PAPER_RECORD = "PAPER_RECORD"
    EMC_REPORT = "EMC_REPORT"
    TEMPERATURE_RECORD = "TEMPERATURE_RECORD"
    AUTOMATION_RECORD = "AUTOMATION_RECORD"
    PUBLISHED_CRITERIA = "PUBLISHED_CRITERIA"
    OTHER = "OTHER"


class TemplateStatus(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    RETIRED = "RETIRED"


class TemplateAuditAction(str, Enum):
    TEMPLATE_UPLOADED = "TEMPLATE_UPLOADED"
    RULE_CREATED = "RULE_CREATED"
    RULE_UPDATED = "RULE_UPDATED"
    RULE_DELETED = "RULE_DELETED"
    TEMPLATE_PUBLISHED = "TEMPLATE_PUBLISHED"
    TEMPLATE_RETIRED = "TEMPLATE_RETIRED"
