<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { useTaskStore } from '../stores/tasks'; import { useTemplateStore } from '../stores/templates'; import ErrorPanel from '../components/ErrorPanel.vue'; import type { SupportingUpload } from '../domain/types';
const router=useRouter(), tasks=useTaskStore(), templates=useTemplateStore(); const templateId=ref(''), primary=ref<File|null>(null), supports=ref<SupportingUpload[]>([])
const evidenceKinds=[['JIRA_RECORD','JIRA 记录'],['PREVIOUS_STAGE_REPORT','上一阶段报告'],['POWER_RECORD','功耗记录'],['REQUIREMENT_OR_CASE_MAPPING','需求/用例映射'],['PAPER_RECORD','纸档记录'],['EMC_REPORT','EMC 报告'],['TEMPERATURE_RECORD','温度记录'],['AUTOMATION_RECORD','自动化记录'],['PUBLISHED_CRITERIA','已发布判据'],['OTHER','其他']] as const
onMounted(async()=>{ try { await templates.loadTemplates(); templateId.value=templates.publishedTemplates[0]?.id ?? '' } catch { /* error is shown below */ } })
const canSubmit=computed(()=>!!templateId.value && !!primary.value && !tasks.loading)
function pickPrimary(event:Event){ primary.value=(event.target as HTMLInputElement).files?.[0] ?? null }
function pickSupports(event:Event){ supports.value=Array.from((event.target as HTMLInputElement).files ?? []).map(file=>({file,evidenceKinds:['OTHER']})) }
async function submit(){ if(!primary.value)return; const task=await tasks.createAndExecute({templateId:templateId.value,primaryReport:primary.value,supportingFiles:supports.value}); await router.push(`/tasks/${task.id}`) }
</script>
<template><section class="page-stack narrow"><header class="page-header"><div><p class="eyebrow">新建任务</p><h1>创建硬件测试报告审核</h1><p>原报告不会被修改；完成后可导出由智能体填写的检查表副本。</p></div></header><ErrorPanel :error="tasks.error ?? templates.error" @dismiss="tasks.clearError"/><form class="panel form-stack" @submit.prevent="submit"><label><span>审核模板</span><select v-model="templateId" required><option value="" disabled>请选择已发布模板</option><option v-for="item in templates.publishedTemplates" :key="item.id" :value="item.id">{{ item.name }} · {{ item.version }}</option></select></label><label><span>主测试报告（PDF、DOC/DOCX、XLS/XLSX）</span><input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" required @change="pickPrimary"></label><label><span>外部证据（可选，可多选）</span><input type="file" multiple @change="pickSupports"></label><ul v-if="supports.length" class="file-list evidence-file-list"><li v-for="item in supports" :key="item.file.name"><span>{{ item.file.name }}</span><select v-model="item.evidenceKinds[0]" aria-label="证据类型"><option v-for="kind in evidenceKinds" :key="kind[0]" :value="kind[0]">{{ kind[1] }}</option></select></li></ul><div class="callout">必需外部证据未提供时，系统判为“不符合”；人工可修改状态，但必须填写修改原因。</div><button class="btn btn-primary" :disabled="!canSubmit">{{ tasks.loading ? '正在创建…' : '创建并开始审核' }}</button></form></section></template>
