<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted } from 'vue'; import { useRoute } from 'vue-router'; import { useTaskStore } from '../stores/tasks'; import StatusBadge from '../components/StatusBadge.vue'; import ErrorPanel from '../components/ErrorPanel.vue';
const route=useRoute(), store=useTaskStore(); const id=String(route.params.taskId); let timer:number|undefined
async function refresh(){ await store.loadTask(id); if(store.isSelectedTransient) timer=window.setTimeout(refresh,2000) }
onMounted(refresh); onBeforeUnmount(()=>timer&&clearTimeout(timer)); const task=computed(()=>store.selected)
const retryWaitMinutes=computed(()=>Math.max(1,Math.ceil((store.selected?.execution?.seconds_until_reclaimable??0)/60)))
async function reexecute(){ await store.reexecute(id).catch(()=>undefined) }
</script>
<template><section v-if="task" class="page-stack"><header class="page-header"><div><p class="eyebrow">任务详情</p><h1>{{ task.display_name }}</h1><p>{{ task.template_name }} · {{ task.template_version }} · {{ task.template_rule_count }} 个校验项</p></div><StatusBadge :status="task.state" /></header><ErrorPanel :error="store.error" @dismiss="store.clearError"/><div v-if="store.isSelectedTransient" class="callout">智能体正在处理，页面每 2 秒自动刷新。</div><article v-if="task.execution" class="panel failure-panel"><h2>执行已中断</h2><p v-if="task.execution.reclaimable">上次执行被中断，任务可以重新执行；已暂存的文件不会丢失。</p><p v-else>上次执行被中断。为避免与可能仍在运行的执行冲突，需等待执行租约到期后再重试（约 {{ retryWaitMinutes }} 分钟）。</p><div class="button-row"><button class="btn btn-primary" type="button" :disabled="!task.execution.reclaimable || store.loading" @click="reexecute">重新执行</button></div></article><article v-if="task.stage_failures.length" class="panel failure-panel"><h2>处理异常</h2><div v-for="failure in task.stage_failures" :key="failure.id"><strong>{{ failure.code }}</strong><p>{{ failure.message }}</p></div></article><div class="two-column"><article class="panel"><h2>输入文件</h2><ul class="file-list"><li v-for="file in task.source_files" :key="file.id"><strong>{{ file.original_name }}</strong><span>{{ file.role === 'PRIMARY_REPORT' ? '主报告' : '外部证据' }} · {{ Math.ceil(file.size_bytes/1024) }} KB</span></li></ul></article><article class="panel"><h2>审核动作</h2><p v-if="task.state==='READY_FOR_REVIEW'">系统审核已完成，请进入审核结果处理待人工确认项。</p><div class="button-row"><RouterLink v-if="['READY_FOR_REVIEW','COMPLETED'].includes(task.state)" class="btn btn-primary" :to="`/tasks/${id}/review`">查看审核结果</RouterLink><a v-if="task.state==='COMPLETED'" class="btn btn-secondary" :href="`/api/tasks/${id}/export`">导出测试检查表</a></div></article></div></section><p v-else class="loading-state">正在读取任务…</p></template>
